apiVersion: v1
kind: Namespace
metadata:
  name: bank-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-app
  namespace: bank-app
  labels:
    app: bank-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-app
  template:
    metadata:
      labels:
        app: bank-app
    spec:
      containers:
        - name: bank-app
          image: <AWS_ACCOUNT_ID>.dkr.ecr.ap-southeast-1.amazonaws.com/bank-app:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secret
          ports:
            - name: http
              containerPort: 3000