apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bank-db-secret
  namespace: bank-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: db-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: bank-db-secret
        property: password
