apiVersion: v1
kind: Service
metadata:
  name: bank-app-service
  namespace: bank-app
spec:
  type: LoadBalancer
  selector:
    app: bank-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080